server:
  port: 8080
dubbo:
  application:
    name: consumer
  registry:
    protocol: zookeeper
    address: 172.16.45.130
    port: 2181
    timeout: 3000

spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password:

rocketmq:
  name-server: 172.16.45.130:9876
